language: ruby
rvm:
  - 1.9.3

script:
  - bundle exec rspec spec
  - bundle exec cucumber
  - bundle exec cane
  - bundle exec metric_fu

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
